---
- name: "update apt packages"
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: "remove unused dependences"
  apt:
    autoremove: yes

- name: "install nodejs"
  apt:
    install nodejs
    
- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
    state: present
    production: yes

- name: "Backend app dir creation"
  file:
    path: ~/backend-app
    state: directory

- name: "Decompress backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing node dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Excute node app and PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Start pm2 as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
